name: Deploy Next.js to Shared Hosting

on:
  push:
    branches:
      - main # Jalankan otomatis saat push ke branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Prepare Deployment Folder
        run: |
          mkdir deploy_ready
          cp -r .next deploy_ready/
          cp -r public deploy_ready/
          cp package.json deploy_ready/
          cp package-lock.json deploy_ready/
          cp next.config.mjs deploy_ready/
          cp server.js deploy_ready/

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Sync Files via LFTP
        run: |
          lftp -e "set ssl:verify-certificate no; open ${{ secrets.FTP_SERVER }}; user ${{ secrets.FTP_USERNAME }} '${{ secrets.FTP_PASSWORD }}'; mirror -R --parallel=5 --exclude-glob .git* --exclude-glob .github* ./deploy_ready/ /; quit"
